$(document).ready(function(){
    $(".one").owlCarousel({
        items:3,
        margin:20,
    });
  });
  $(document).ready(function(){
    $(".two").owlCarousel({
        items:3,
        margin:20,
    });
  });